//  Add all the fonts here
const Fonts = {
  IBMFonts: {
    IBMPlexMono_Bold: 'IBMPlexMono-Bold',
    IBMPlexMono_BoldItalic: 'IBMPlexMono-BoldItalic',
    IBMPlexMono_ExtraLight: 'IBMPlexMono-ExtraLight',
    IBMPlexMono_ExtraLightItalic: 'IBMPlexMono-ExtraLightItalic',
    IBMPlexMono_Italic: 'IBMPlexMono-Italic',
    IBMPlexMono_Light: 'IBMPlexMono-Light',
    IBMPlexMono_LightItalic: 'IBMPlexMono-LightItalic',
    IBMPlexMono_Medium: 'IBMPlexMono-Medium',
    IBMPlexMono_MediumItalic: 'IBMPlexMono-MediumItalic',
    IBMPlexMono_Regular: 'IBMPlexMono-Regular',
    IBMPlexMono_SemiBold: 'IBMPlexMono-SemiBold',
    IBMPlexMono_SemiBoldItalic: 'IBMPlexMono-SemiBoldItalic',
    IBMPlexMono_Thin: 'IBMPlexMono-Thin',
    IBMPlexSans_Bold: 'IBMPlexSans-Bold',
    IBMPlexSans_BoldItalic: 'IBMPlexSans-BoldItalic',
    IBMPlexSans_ExtraLight: 'IBMPlexSans-ExtraLight',
    IBMPlexSans_ExtraLightItalic: 'IBMPlexSans-ExtraLightItalic',
  },
  LatoFonts: {
    Lato_Black: 'Lato-Black',
    Lato_BlackItalic: 'Lato-BlackItalic',
    Lato_Bold: 'Lato-Bold',
    Lato_BoldItalic: 'Lato-BoldItalic',
    Lato_Hairline: 'Lato-Hairline',
    Lato_Heavy: 'Lato-Heavy',
    Lato_Light: 'Lato-Light',
    Lato_Medium: 'Lato-Medium',
    Lato_Regular: 'Lato-Regular',
    Lato_Semibold: 'Lato-Semibold',
  },
  SansSerifFonts: {
    ss_medium: 'SharpSans-Medium',
    ss_semiBold: 'SharpSans-Semibold',
    ss_book: 'SharpSans-Book',
    ssd_black: 'SharpSansDisplayNo1-Black',
    ssd_bold: 'SharpSansDisplayNo1-Bold',
    ssd_book: 'SharpSansDisplayNo1-Book',
    ssd_extraBold: 'SharpSansDisplayNo1-ExtraBold',
    ssd_hairline: 'SharpSansDisplayNo1-Hairline',
    ssd_medium: 'SharpSansDisplayNo1-Medium',
    ssd_semiBold: 'SharpSansDisplayNo1-Semibold',
    ssd_thin: 'SharpSansDisplayNo1-Thin',
    ssd_ultraThin: 'SharpSansDisplayNo1-Ultrathin',
  },
};

export default Fonts;
